// Generated by CoffeeScript 1.4.0
var address, file, fs, output, page, system, _ref;

page = require("webpage").create();

system = require("system");

fs = require("fs");

if (system.args.length < 3 || system.args.length > 5) {
  console.log("Usage: phantomjs --load-images=no html.js URL filename");
  phantom.exit(1);
} else {
  _ref = system.args, file = _ref[0], address = _ref[1], output = _ref[2];
  page.open(address, function(status) {
    if (status !== "success") {
      console.log("Unable to load the address! (" + address + ")");
    } else {
      fs.write(output, page.content, "w");
    }
    return phantom.exit();
  });
}
