// Generated by CoffeeScript 1.4.0
var fs, listening, page, port, server, system, url;

page = require("webpage").create();

server = require("webserver").create();

system = require("system");

url = require("url");

fs = require('fs');

if (system.args.length !== 2) {
  console.log("Usage: phantomjs --load-images=no server.js <port>");
  phantom.exit(1);
} else {
  port = system.args[1];
  listening = server.listen(port, function(request, response) {
    var address, filename, queryString;
    if (!request.url.match(/favicon/)) {
      queryString = url.parse(request.url, true).query;
      address = queryString.url;
      if (queryString.filename != null) {
        filename = queryString.filename;
      }
      response.statusCode = 200;
      response.setEncoding('utf8');
      response.headers = {
        "Cache": "no-cache",
        "Content-Type": "text/html"
      };
      console.log("SENDING REQUEST TO: " + address);
      return page.open(address, function(status) {
        if (status !== "success") {
          response.write("FAILED to load the address: " + address);
        } else {
          console.log("GOT REPLY FROM SERVER!");
          response.write(page.content);
          if (filename) {
            fs.write(filename, page.content, "w");
          }
        }
        return response.close();
      });
    }
  });
  if (!listening) {
    console.log("could not create web server listening on port " + port);
    phantom.exit();
  }
}
